name = "kabir-sant-sharan"
main = "src/index.ts"
compatibility_date = "2024-09-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[env.production]
name = "kabir-sant-sharan"

[env.staging]
name = "kabir-sant-sharan-staging"

[[d1_databases]]
binding = "DB"
database_name = "kabir-sant-sharan"
database_id = "cf50986b-cc78-4c0c-b6bd-268e6b8c44c5"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "kabir-media"
preview_bucket_name = "kabir-media-dev"

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_APP_URL = "https://kabir-sant-sharan.pages.dev"
NEXT_PUBLIC_SITE_NAME = "Kabir Sant Sharan"

[env.staging.vars]
ENVIRONMENT = "staging"
NEXT_PUBLIC_APP_URL = "https://kabir-sant-sharan-staging.pages.dev"
NEXT_PUBLIC_SITE_NAME = "Kabir Sant Sharan (Staging)"

[triggers]
crons = ["0 9 * * *"]

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "kabir_analytics"

[placement]
mode = "smart"

[limits]
cpu_ms = 50

