name = "kabir-sant-sharan"
compatibility_date = "2024-09-29"
pages_build_output_dir = "out"

[env.production]
name = "kabir-sant-sharan"

[[env.production.d1_databases]]
binding = "DB"
database_name = "kabir-sant-sharan"
database_id = "cf50986b-cc78-4c0c-b6bd-268e6b8c44c5"

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "kabir-media"

[env.production.vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_APP_URL = "https://kabirsantsharan.com"
NEXT_PUBLIC_SITE_NAME = "Kabir Sant Sharan"

[env.preview]
name = "kabir-sant-sharan-preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "kabir-sant-sharan"
database_id = "cf50986b-cc78-4c0c-b6bd-268e6b8c44c5"

[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "kabir-media-dev"

[env.preview.vars]
ENVIRONMENT = "preview"
NEXT_PUBLIC_APP_URL = "https://kabir-sant-sharan.pages.dev"
NEXT_PUBLIC_SITE_NAME = "Kabir Sant Sharan (Preview)"